// The doctrine, in the form that can actually be obeyed.  dd-016.
//
// design-doctrine.json stores lessons as prose - trigger, verbatim, reasoning,
// test.  That shape carries the WHY and must be kept.  It is also the wrong
// shape at the moment of designing, when what is needed is one imperative line
// a builder can check without re-reading a paragraph.  dd-012 is the proof:
// dd-009 and dd-010 were recorded, cited by id in the rung's own checks file,
// and violated in that same rung.  The citation was honest; it just was not an
// instruction.
//
// So every entry now carries `do` and `dont` arrays, and this script projects
// them into one flat page.  The page is GENERATED, never maintained - dd-013:
// the simple surface is a projection of the source, not a second copy of it.
//
//   node scripts/doctrine-rules.js            write docs/doctrine-rules.md
//   node scripts/doctrine-rules.js --check    fail if that file is stale
//   node scripts/doctrine-rules.js checks X   write a .checks.md skeleton for X
//
import fs from 'node:fs';
import path from 'node:path';

const SRC = 'src/data/design-doctrine.json';
const OUT = 'docs/doctrine-rules.md';
const CALC_DIR = 'src/components/Calculators';

// A surface is a place a rule can be broken.  An entry belongs to one when its
// own `applies_to` says so - entries govern where they claim to govern, and the
// list is not curated here.  `scope: "process"` marks the entries that govern
// how we keep records rather than how a screen reads; they apply to the work,
// not to any one screen, so they are not part of a component's checklist.
const SURFACE_PATTERNS = [
  /calculator/i,
  /interactive component/i,
  /workbench/i,
  /every screen/i,
  /whole product/i,
  /toggle|tab|mode/i,
  /slider|stepper|dial/i,
  /figure projected forward/i,
  /exists for the tail/i,
  /more than one view/i,
];

export function loadDoctrine() {
  return JSON.parse(fs.readFileSync(SRC, 'utf-8'));
}

/** Entries a calculator screen must answer to. */
export function applicableToCalculators(doctrine) {
  return doctrine.filter((e) => {
    if (e.scope === 'process') return false;
    const applies = e.applies_to ?? [];
    return applies.some((a) => SURFACE_PATTERNS.some((p) => p.test(a)));
  });
}

/** Stable ids: dd-012/dont-2 addresses one line, not a paragraph. */
export function rulesOf(entry) {
  const out = [];
  (entry.do ?? []).forEach((t, i) => out.push({ id: `${entry.id}/do-${i + 1}`, kind: 'do', text: t }));
  (entry.dont ?? []).forEach((t, i) => out.push({ id: `${entry.id}/dont-${i + 1}`, kind: 'dont', text: t }));
  return out;
}

export function render(doctrine) {
  const calc = applicableToCalculators(doctrine);
  const L = [];

  L.push('# The doctrine as do\'s and don\'ts');
  L.push('');
  L.push('**Generated by `npm run doctrine`. Do not edit — edit `src/data/design-doctrine.json`.**');
  L.push('');
  L.push(
    'The reasoning, the trigger and Rahul\'s verbatim words live in the JSON and are ' +
      'the part worth reading twice. This page is the other half: the same lessons ' +
      'reduced to lines you can check a screen against without re-reading an essay. ' +
      'dd-016 exists because a cited principle is not an instruction.'
  );
  L.push('');
  L.push(`${doctrine.length} entries · ${doctrine.reduce((n, e) => n + rulesOf(e).length, 0)} rules · ${calc.length} entries bind any calculator screen`);
  L.push('');
  L.push('---');
  L.push('');

  // The working checklist first.  This is what gets read under pressure, so it
  // is at the top and it is only the don'ts - the failures, not the aspirations.
  L.push('## Before you design a calculator screen');
  L.push('');
  L.push('Every one of these must be answered by id in the component\'s `.checks.md`.');
  L.push('Generate the skeleton with `npm run doctrine:checks <ComponentName>`.');
  L.push('');
  for (const e of calc) {
    for (const r of rulesOf(e).filter((r) => r.kind === 'dont')) {
      L.push(`- \`${r.id}\` ${r.text}`);
    }
  }
  L.push('');
  L.push('---');
  L.push('');
  L.push('## Every entry');
  L.push('');

  for (const e of doctrine) {
    L.push(`### ${e.id} — ${e.title}`);
    L.push('');
    const where = e.scope === 'process' ? 'process — how we keep records' : (e.applies_to ?? ['—']).join(' · ');
    L.push(`*${where}*`);
    L.push('');
    if (e.do?.length) {
      L.push('**Do**');
      L.push('');
      for (const r of rulesOf(e).filter((r) => r.kind === 'do')) L.push(`- \`${r.id}\` ${r.text}`);
      L.push('');
    }
    if (e.dont?.length) {
      L.push('**Don\'t**');
      L.push('');
      for (const r of rulesOf(e).filter((r) => r.kind === 'dont')) L.push(`- \`${r.id}\` ${r.text}`);
      L.push('');
    }
    L.push(`> **Test.** ${e.test}`);
    L.push('');
  }

  return L.join('\n');
}

/** A skeleton with every applicable rule pre-filled: answering is the cost, not typing. */
export function renderChecksSkeleton(doctrine, component) {
  const calc = applicableToCalculators(doctrine);
  const L = [];
  L.push(`# Design checks — ${component}`);
  L.push('');
  L.push('**Written before the component.**');
  L.push('');
  L.push('**Question:** *TODO — the one question of the reader\'s that this step answers.*');
  L.push('');
  L.push('## Doctrine rules — answered');
  L.push('');
  L.push('PASS and RISK need a reason. N/A may stand alone.');
  L.push('');
  L.push('| rule | verdict | why |');
  L.push('|---|---|---|');
  for (const e of calc) {
    for (const r of rulesOf(e).filter((r) => r.kind === 'dont')) {
      L.push(`| ${r.id} | TODO | ${r.text} |`);
    }
  }
  L.push('');
  L.push('## Deliberate choices');
  L.push('');
  L.push('- TODO');
  L.push('');
  return L.join('\n');
}

// --- cli ---------------------------------------------------------------
// Guarded: the test suite imports render() and must not trip over vitest's argv.
const isCli = !!process.argv[1] && path.basename(process.argv[1]) === 'doctrine-rules.js';
const [cmd, arg] = process.argv.slice(2);

if (!isCli) {
  // imported as a module - nothing to do
} else if (cmd === 'checks') {
  if (!arg) {
    console.error('usage: npm run doctrine:checks <ComponentName>');
    process.exit(1);
  }
  const file = path.join(CALC_DIR, `${arg}.checks.md`);
  if (fs.existsSync(file)) {
    console.error(`${file} already exists - refusing to overwrite an answered checks file.`);
    process.exit(1);
  }
  fs.writeFileSync(file, renderChecksSkeleton(loadDoctrine(), arg));
  console.log(`Wrote ${file}. Answer every TODO before writing the component (dd-000).`);
} else if (cmd === '--check') {
  const want = render(loadDoctrine());
  const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf-8') : '';
  if (want !== have) {
    console.error(`${OUT} is stale. Run: npm run doctrine`);
    process.exit(1);
  }
  console.log(`${OUT} is current.`);
} else {
  fs.writeFileSync(OUT, render(loadDoctrine()));
  console.log(`Wrote ${OUT}`);
}
